### ISSUE TITLE
Deprecated selector in `spectrum-light-syntax\index.less`

### ISSUE THREAD

**Issue by kostadinnm** [adcoulter/spectrum-light-syntax#1]
Hello
I decided to use this theme as a higher-contrast variant of the build-in [base-16-tomorrow-light](https://github.com/atom/base16-tomorrow-light-theme). I did some mods(background, comments' and json colors), but I now realize that it uses some older selectors as a tool called **deprication cop** pops up with the following message:

> In `spectrum-light-syntax\index.less`: 
> 
> Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

- >atom-text-editor::shadow .bracket-matcher .region => atom-text-editor.editor .bracket-matcher .region

- >atom-text-editor.is-focused::shadow .cursor-line => atom-text-editor.is-focused.editor .cursor-line

...
and the list of example migrations continues, but what's vital is that they're going to remove the support for those selectors soon:
> Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

Your dark theme seems to be free of `host:` calls, could you update this as well!?

Cheers,
Kostadin

**Comment by adcoulter** [comment]
Been a while since I've used a light theme so it totally slipped my mind. I'll get this fixed, thanks for letting me know :)

**Comment by adcoulter** [comment]
fixed! ff292ce4e0568e54f3ba28ca44defe15d4b28fa6
